### ISSUE TITLE
Multiple tests fail due to rounding errors

### ISSUE THREAD

**Issue by nicholascar** [manaakiwhenua/rhealpixdggs-py#1]
In release 0.51, multiple unit and doc tests fail due to seemingly trivial rounding errors, e.g.:

in [dggs.py, line 518](https://github.com/manaakiwhenua/rhealpixdggs-py/blob/master/rhealpixdggs/dggs.py#L518),

The function, `xyz_cube`, has this documentation:

```python
>>> print(my_round(rdggs.xyz_cube(0, 0), 14))
(0.78539816339745006, 0.0, -0.78539816339745006)
```

Which has 17 decimal paces given, however, when run, the computed answer is:

```python
(0.78539816339745, 0.0, -0.78539816339745)
```

which has 14 decimal places, as advertised it should have due to the `my_round()` function.

17 decimal places is the Python default. Changing the rounding to 17 doesn't fix this error as the computed result is slightly different from the given, comparison, value.

This issue is relevant for many tests.

**PROPOSED SOLUTION**:

Round all the comparison values to 14 decimal places.

**Comment by rggibb** [comment]
All rounding tests have been corrected so that the length of the expected result matches the rounding applied by my_round(). Typically 14 or 15. 
Once exception remains and that is pj_isea.py, where the results bear no relation to the expected reult.

**Comment by nicholascar** [comment]
In addition to the three UnitTest tests still failing, there are still rounding errors in 10 of the 49 doctests for the file introduction.rst:

```
python -m doctest docs/source/introduction.rst
```

Some of these a a little further off than those you've solved so I'm not able to just apply the same fixes you have without knowing I might be breaking something, e.g.:

```
File "docs/source/introduction.rst", line 75, in introduction.rst
Failed example:
    print(ellps_2)
Expected:
    ellipsoid:
        R_A = 4.32200117119
        a = 5
        b = 3.0
        e = 0.8
        f = 0.4
        lat_0 = 0
        lon_0 = 0
        radians = True
        sphere = False
Got:
    ellipsoid:
        R_A = 4.322001171188888
        a = 5
        b = 2.999999999999999
        e = 0.8
        f = 0.4
        lat_0 = 0
        lon_0 = 0
        radians = True
        sphere = False
```

This example's clearly a rounding error for `R_A` and a float/decimal conversion issue for `b` but I don't know enough to be able to say which things should be altered - the expected output (a `b` value of 2.9999... seems bad) or the function to return a different result.

Also, the following Python file contain failures that seem substantial:

* **rhealpixdggs/pj_isea.py** - 2 of 4 tests fail

```
File "rhealpixdggs/pj_isea.py", line 103, in pj_isea.isea
Failed example:
    print(my_round(f(0, pi/3, radians=True), 15))
Expected:
    (-4.7097959155097699, 2.9195761776404252)
Got:
    (-0.417419095135028, 1.077342160052412)


File "rhealpixdggs/pj_isea.py", line 106, in pj_isea.isea
Failed example:
    print(my_round(g(0, 60, radians=False), 15))
Expected:
    (-4.6978889550868486, 2.9179977608222689)
Got:
    (-0.416723049323654, 1.075446904085452)
```

**Comment by rggibb** [comment]
I had thought that introduction.rst was generated by sphinx from the documentation blocks in the .py files and that therefore running sphinx (which I havent done) was the prefered means to fix the errors in introduction.rst .. is that not the case?

.. and yes pj_isea.py is a worry, since the differences are very significant. Having said that pj_isea.py is only used to generate diagrams and data for figures in the paper, and not for generating rhealpix dggs, so in a sense it is a side issue, We _could_ move most of the home-made projections into the [repo for the paper](https://github.com/manaakiwhenua/rhealpixdggs-2013-gibb-raichev-speth).

**Comment by nicholascar** [comment]
> I had thought that introduction.rst was generated by sphinx from the documentation blocks in the

Not `introduction.rst` - that's a source reStructuredText file that is used for documentation generation itself. Examples in the module's Python files such as `dggs.py` will be used in the auto documentation generation.

I've not run Shinx yet - waiting to address these issues.

> pj_isea.py is only used to generate diagrams and data for figures in the paper, and not for generating rhealpix dggs

Let's do shift it then please! We need to get this code down to the essential code with tests and nothing else in the primary PyPI module. We can have ancillary files in the package as a whole but the rhealpixdggs/ folder really should be functioning code only. That's the pip installed bit.
