### ISSUE TITLE
Seperate out analyze_distortion, distortion, isea, csea, qsc, zot

### ISSUE THREAD

**Issue by rggibb** [manaakiwhenua/rhealpixdggs-py#2]
> pj_isea.py is only used to generate diagrams and data for figures in the paper, and not for generating rhealpix dggs

Let's do shift it then please! We need to get this code down to the essential code with tests and nothing else in the primary PyPI module. We can have ancillary files in the package as a whole but the rhealpixdggs/ folder really should be functioning code only. That's the pip installed bit.

_Originally posted by @nicholascar in https://github.com/manaakiwhenua/rhealpixdggs-py/issues/1#issuecomment-658469665_

**Comment by rggibb** [comment]
I'm going to shift these to [rhealpixdggs-2013-gibb-raichev-speth](https://github.com/manaakiwhenua/rhealpixdggs-2013-gibb-raichev-speth), because they are used to generate the diagrams and proj statistics for that paper. 
I'll also move their test suits and their documentation sections, and split the documentation into two parts, so that both parts generate appropriate documents.
I'll leave projection_wrapper-py, and the pj_healpix and pj_rhealpix homemade projections where they are, and raise an issue to flag that we need to check whether the versions of healpix and [rhealpix](https://proj.org/operations/projections/rhealpix.html) in proj.4 (now proj.7) can be used. At the time the code was last checked by Alex Raichev, the code in proj wasnt yet working, so the homemade version here had to be used.

**Comment by rggibb** [comment]
@nicholascar I think this is now done, as a consequence can you please
1. remove references to SageMath in the readme, maybe point to the existence of the distortion analysis package and the proj test graphics from SageMath both being in [rhealpixdggs-2013-gibb-raichev-speth](https://github.com/manaakiwhenua/rhealpixdggs-2013-gibb-raichev-speth).
2. check to see if the unit tests are in better shape.

**Comment by alpha-beta-soup** [comment]
I suspect there are still correctness issues with the rhealpix implementation in PROJ. The Python library still uses the implementations within this repository over PROJ, but it would be good to move away from them. Shall I make an issue for that specifically @rggibb?
