### ISSUE TITLE
Check whether homemade rhealpix and healpix can be replaced by proj versions.

### ISSUE THREAD

**Issue by rggibb** [manaakiwhenua/rhealpixdggs-py#3]
I'll leave projection_wrapper-py, and the pj_healpix and pj_rhealpix homemade projections where they are, and raise an issue to flag that we need to check whether the versions of healpix and [rhealpix](https://proj.org/operations/projections/rhealpix.html) in proj.4 (now proj.7) can be used. At the time the code was last checked by Alex Raichev, the code in proj wasnt yet working, so the homemade version here had to be used.

_Originally posted by @rggibb in https://github.com/manaakiwhenua/rhealpixdggs-py/issues/2#issuecomment-658517671_

**Comment by ndemaio** [comment]
This is now in progress, with fairly...explosive...results so far. We'll keep picking at it until we know more.

**Comment by alpha-beta-soup** [comment]
See https://github.com/manaakiwhenua/rhealpixdggs-py/pull/22

Particularly:

> Decided **against** using the healpix/rhealpix projections from pyproj/PROJ - they break our tests in significant ways and it looks like whatever bugs were there in 2013 haven't been fixed
